language: php

sudo: false

notifications:
  email:
    on_success: never

php:
  - 7.3
  - 7.4
  - nightly

env:
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""

stages:
  - test
  - test with coverage

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - composer self-update

install: travis_retry composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest $COMPOSER_FLAGS -vv

script: vendor/bin/phpunit --colors --columns 117 --no-coverage

jobs:
  allow_failures:
    - php: nightly
  include:
    - php: nightly
      env: COMPOSER_FLAGS="--ignore-platform-reqs"

    - stage: test with coverage
      os: linux
      php: 7.3
      env: COMPOSER_FLAGS=""
      before_install: composer self-update
      script: vendor/bin/phpunit --colors --coverage-text
